# Generated by Django 3.2.7 on 2022-04-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photos',
        ),
    ]
